import Foundation

/// Provides localized string lookup. The app is English-only; this exists
/// to centralize string-table access through `Bundle.appResources`.
@Observable
final class LanguageManager: @unchecked Sendable {
    static let shared = LanguageManager()

    private let bundle: Bundle

    init() {
        self.bundle = Self.resolveBundle()
    }

    // MARK: - Localized string access

    /// Look up a localized string by key.
    func t(_ key: String) -> String {
        bundle.localizedString(forKey: key, value: key, table: nil)
    }

    /// Look up a localized format string and apply arguments.
    func t(_ key: String, _ args: any CVarArg...) -> String {
        let format = bundle.localizedString(forKey: key, value: key, table: nil)
        return String(format: format, arguments: args)
    }

    // MARK: - Private

    private static func resolveBundle() -> Bundle {
        // Bundle.appResources is auto-generated by SPM when resources are declared.
        // SPM `.process()` may lowercase lproj directory names, and
        // Bundle.path(forResource:ofType:) is case-sensitive, so try both variants.
        for candidate in ["en", "En"] {
            if let path = Bundle.appResources.path(forResource: candidate, ofType: "lproj"),
               let localized = Bundle(path: path) {
                return localized
            }
        }

        return Bundle.appResources
    }
}
